#pragma once

#define IDR_FONT_TEXT_REGULAR   101
#define IDR_FONT_TEXT_MEDIUM    102
#define IDR_FONT_ICON_SYMBOL    103
#define IDR_FONT_ICON_BRAND     104
#define IDR_FONT_ICON_AWESOME   105
#define IDR_IMAGE_SETTINGS_GEAR 202
#define IDR_IMAGE_MISC_GLOBE    203
#define IDR_IMAGE_EXPLOITS_BOMB 204
#define IDR_IMAGE_VISUALS_EYE   205
#define IDR_IMAGE_VISUALS_BODY  206
#define IDR_IMAGE_VISUALS_INFO  207
#define IDR_IMAGE_VISUALS_LAYER 208
#define IDR_IMAGE_VISUALS_MAP   209
#define IDR_IMAGE_AIMBOT_CROSSHAIRS 210
#define IDR_IMAGE_AIMBOT_GLOBAL     211
#define IDR_IMAGE_AIMBOT_SILENT     212
#define IDR_IMAGE_AIMBOT_TRIGGER    213
#define IDR_IMAGE_WEAPON_SHOTGUN    214
#define IDR_IMAGE_WEAPON_AR         215
#define IDR_IMAGE_WEAPON_SMG        216
#define IDR_IMAGE_WEAPON_PISTOL     217
#define IDR_IMAGE_WEAPON_SNIPER     218
